import React, { createContext, useContext, useState, useEffect } from 'react';
import { safeStorage } from '@/utils/safeStorage';

export type Language = 'en' | 'th';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.orders': 'Orders',
    'nav.menu': 'Menu',
    'nav.settings': 'Settings',
    'nav.sales': 'Sales',
    'nav.logout': 'Logout',
    'header.dashboard': 'Back Office',
    
    // Orders
    'orders.title': 'Orders Dashboard',
    'orders.all': 'All Orders',
    'orders.new': 'New Orders',
    'orders.preparing': 'Preparing',
    'orders.ready': 'Ready',
    'orders.completed': 'Completed',
    'orders.refresh': 'Refresh',
    'orders.viewDetails': 'View Details',
    'orders.total': 'Total',
    'orders.noOrders': 'No orders found',
    'orders.confirmCancel': 'Cancel this order? This cannot be undone.',
    'orders.orderedAt': 'Order at',
    
    // Order Status
    'status.pending': 'Pending',
    'status.preparing': 'Preparing',
    'status.ready': 'Ready',
    'status.completed': 'Completed',
    'status.cancelled': 'Cancelled',
    
    // Order Actions
    'action.startPreparing': 'Start Preparing',
    'action.markReady': 'Mark Ready',
    'action.completeOrder': 'Complete Order',
    'action.updating': 'Updating...',
    
    // Order Details
    'orderDetails.title': 'Order',
    'orderDetails.status': 'Order Status',
    'orderDetails.items': 'Order Items',
    'orderDetails.customer': 'Customer Information',
    'orderDetails.details': 'Order Details',
    'orderDetails.print': 'Print',
    'orderDetails.date': 'Order Date',
    'orderDetails.time': 'Order Time',
    'orderDetails.payment': 'Payment',
    'orderDetails.paymentMethod': 'Cash on Pickup',
    'orderDetails.specialInstructions': 'Special Instructions',
    'orderDetails.totalAmount': 'Total Amount',
    'orderDetails.each': 'each',
    
    // Sales
    'sales.title': 'Sales Dashboard',
    'sales.totalOrders': 'Total Orders',
    'sales.totalRevenue': 'Total Revenue',
    'sales.avgOrderValue': 'Avg Order Value',
    'sales.date': 'Date',
    'sales.topItems': 'Top Selling Items',
    'sales.export': 'Export',
    'sales.insights': 'Sales Insights',
    'sales.performance': 'Performance',
    'sales.noData': 'No sales data available',
    
    // Menu
    'menu.title': 'Menu Management',
    'menu.addItem': 'Add Item',
    'menu.search': 'Search menu items...',
    'menu.allCategories': 'All Categories',
    'menu.allItems': 'All Items',
    'menu.availableOnly': 'Available Only',
    'menu.unavailableOnly': 'Unavailable Only',
    'menu.available': 'Available',
    'menu.unavailable': 'Unavailable',
    'menu.hide': 'Hide',
    'menu.show': 'Show',
    'menu.noItems': 'No menu items found',
    'menu.unavailableLabel': 'UNAVAILABLE',
    
    // Menu Form
    'menuForm.addTitle': 'Add New Menu Item',
    'menuForm.editTitle': 'Edit Menu Item',
    'menuForm.name': 'Name',
    'menuForm.nameRequired': 'Name *',
    'menuForm.nameEn': 'Name (English) *',
    'menuForm.nameTh': 'Name (Thai) *',
    'menuForm.namePlaceholder': 'Item name',
    'menuForm.nameEnPlaceholder': 'Item name in English',
    'menuForm.nameThPlaceholder': 'Item name in Thai',
    'menuForm.description': 'Description',
    'menuForm.descriptionEn': 'Description (English)',
    'menuForm.descriptionTh': 'Description (Thai)',
    'menuForm.descriptionPlaceholder': 'Item description (optional)',
    'menuForm.descriptionEnPlaceholder': 'Item description in English (optional)',
    'menuForm.descriptionThPlaceholder': 'Item description in Thai (optional)',
    'menuForm.basePrice': 'Base Price',
    'menuForm.basePriceRequired': 'Base Price *',
    'menuForm.basePricePlaceholder': '0.00',
    'menuForm.category': 'Category',
    'menuForm.categoryRequired': 'Category *',
    'menuForm.categoryEn': 'Category (English) *',
    'menuForm.categoryTh': 'Category (Thai) *',
    'menuForm.categoryPlaceholder': 'e.g., Coffee, Tea, Pastry',
    'menuForm.categoryEnPlaceholder': 'e.g., Coffee, Tea, Pastry',
    'menuForm.categoryThPlaceholder': 'เช่น กาแฟ, ชา, ขนมอบ',
    'menuForm.availability': 'Availability',
    'menuForm.active': 'Active',
    'menuForm.inactive': 'Inactive',
    'menuForm.image': 'Image',
    'menuForm.imageUrl': 'Image URL (optional)',
    'menuForm.uploadImage': 'Upload Image',
    'menuForm.orEnterUrl': 'or enter URL above',
    'menuForm.customizations': 'Customizations',
    'menuForm.addCustomization': 'Add',
    'menuForm.customizationPlaceholder': 'Customization name (e.g., sizes, milk, extras)',
    'menuForm.options': 'Options:',
    'menuForm.addOption': '+ Add Option',
    'menuForm.optionPlaceholder': 'Option value',
    'menuForm.remove': 'Remove',
    'menuForm.saving': 'Saving...',
    'menuForm.uploading': 'Uploading...',
    'menuForm.update': 'Update',
    'menuForm.create': 'Create',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.clear': 'Clear',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.back': 'Back',
    'common.na': 'N/A',
    'common.phone': 'Phone',
    'common.email': 'Email',
    'common.name': 'Name',
    'common.customer': 'Customer',
    'common.add': 'Add',
    'common.select': 'Select',
    'common.unitPrice': 'Unit price',
    'common.refresh': 'Refresh',
    'common.view': 'View',

    // Create Order
    'createOrder.title': 'Create Order',
    'createOrder.menu': 'Menu',
    'createOrder.searchPlaceholder': 'Search menu...',
    'createOrder.customerInfo': 'Customer Information',
    'createOrder.customerNamePlaceholder': 'Customer name',
    'createOrder.phonePlaceholder': 'e.g. 080-000-0000',
    'createOrder.emailPlaceholder': 'email@example.com',
    'createOrder.notes': 'Notes',
    'createOrder.cart': 'Cart',
    'createOrder.cartEmpty': 'No items in the cart. Add from the menu.',
    'createOrder.discountCode': 'Discount Code',
    'createOrder.items': 'Items',
    'createOrder.subtotal': 'Subtotal',
    'createOrder.discount': 'Discount',
    'createOrder.total': 'Total',
    'createOrder.placeOrder': 'Place Order',
    'createOrder.creating': 'Creating...',
    'createOrder.loadingMenu': 'Loading menu...',
    'createOrder.noMenu': 'No menu items found. Please add items in Menu Management first.',
    'createOrder.noDiscount': 'No discount',

    // Settings
    'settings.title': 'Settings',
    'settings.appSettings': 'App Settings',
    'settings.language': 'Language',
    'settings.autoRefreshInterval': 'Auto Refresh Interval (seconds)',
    'settings.currentValue': 'Current value',
    'settings.shop': 'Shop',
    'settings.clientStatus': 'App client status is',
    'settings.refresh': 'Refresh',
    'settings.refreshing': 'Refreshing...',
    'settings.systemInformation': 'System Information',
    'settings.appVersion': 'App Version',
    'settings.lastUpdated': 'Last Updated',
    'settings.browser': 'Browser',
    'settings.platform': 'Platform',
    'settings.saveSettings': 'Save Settings',
    'settings.userProfile': 'User Profile',
    'settings.role': 'Role',

    // Dashboard
    'dashboard.todaysRevenue': "Today's Revenue",
    'dashboard.todaysOrders': "Today's Orders",
    'dashboard.avgOrderValue': 'Avg. Order Value',
    'dashboard.activeOrders': 'Active Orders',
    'dashboard.completionRate': 'Completion Rate',
    'dashboard.recentOrders': 'Recent Orders',
    'dashboard.noOrdersYet': 'No orders yet',
    'dashboard.viewAll': 'View all',
    'dashboard.manageOrders': 'Manage Orders',
    'dashboard.manageOrdersDesc': 'View and update order status',
    'dashboard.menuManagement': 'Menu Management',
    'dashboard.menuManagementDesc': 'Update menu items and prices',
    'dashboard.settings': 'Settings',
    'dashboard.settingsDesc': 'Configure app settings',
    'dashboard.teaCupProgress': 'Tea Cup Progress',
    'dashboard.record': 'Record!',
    'dashboard.vsYesterday': 'vs yesterday',
    'dashboard.toBreak': 'to break',

    // Sales page extra
    // 'sales.title' already defined above
    'sales.hourlyCurve': 'Hourly Sales (Curve)',
    'sales.specificDay': 'Specific day',
    'sales.dateRange': 'Date range',
    'sales.allTime': 'All-time',
    'sales.useDateRange': 'Use Date Range',
    'sales.showAllTime': 'Show All Time',
    'sales.metric': 'Metric',
    'sales.revenue': 'Revenue',
    'sales.orders': 'Orders',
    'sales.itemsSold': 'Items sold',
    'sales.noHourlyData': 'No hourly data.',
    'sales.periodAllTime': 'Sales Period: All time',
    'sales.periodRange': 'Sales Period',
    'sales.to': 'to',
    // 'sales.topItems' already defined above
    'sales.rank': 'Rank',
    'sales.itemName': 'Item Name',
    'sales.category': 'Category',
    'sales.quantitySold': 'Quantity Sold',
    'sales.revenueCol': 'Revenue',
    'sales.percentageOfSales': 'Percentage of Sales',
    'sales.revenueInsights': 'Revenue Insights',
    'sales.completedRevenue': 'Completed Revenue',
    'sales.bestCategory': 'Best selling category',
    'sales.highestRevenueItem': 'Highest revenue item',
    'sales.topItemShare': 'Top item share',
    'sales.orderPerformance': 'Order Performance',
    'sales.cancelledRate': 'Cancelled Rate',
    'sales.orderCompletionProgress': 'Order completion progress',
    'sales.ordersCompleted': 'Orders completed successfully',
    'sales.noDataHint': 'No sales data found for the selected period. Try adjusting your date range.',
    'sales.retry': 'Retry Loading Data',
    'sales.startDate': 'Start Date',
    'sales.endDate': 'End Date',
    'sales.dailyBreakdown': 'Daily Breakdown',
    'sales.items': 'items',
    'sales.found': 'found',
    'sales.totals': 'Totals',
    'sales.day': 'Day',
    'sales.rangeLabel': 'Range',
    'sales.noItemsSold': 'No items were sold.',
    'sales.totalRevenueLower': 'total revenue',
    'sales.avgPrice': 'avg price',
    
    // Common extra
    'common.status': 'Status',
  },
  th: {
    // Navigation
    'nav.dashboard': 'แดชบอร์ด',
    'nav.orders': 'คำสั่งซื้อ',
    'nav.menu': 'เมนู',
    'nav.settings': 'ตั้งค่า',
    'nav.sales': 'ยอดขาย',
    'nav.logout': 'ออกจากระบบ',
    'header.dashboard': 'แดชบอร์ดแบ็คออฟฟิศ',
    
    // Orders
    'orders.title': 'แดชบอร์ดคำสั่งซื้อ',
    'orders.all': 'คำสั่งซื้อทั้งหมด',
    'orders.new': 'คำสั่งซื้อใหม่',
    'orders.preparing': 'กำลังเตรียม',
    'orders.ready': 'พร้อมแล้ว',
    'orders.completed': 'เสร็จสิ้น',
    'orders.refresh': 'รีเฟรช',
    'orders.viewDetails': 'ดูรายละเอียด',
    'orders.total': 'รวม',
    'orders.noOrders': 'ไม่พบคำสั่งซื้อ',
    'orders.confirmCancel': 'ยกเลิกคำสั่งซื้อนี้? ไม่สามารถย้อนกลับได้',
    'orders.orderedAt': 'เวลาสั่งซื้อ',
    
    // Order Status
    'status.pending': 'รอดำเนินการ',
    'status.preparing': 'กำลังเตรียม',
    'status.ready': 'พร้อมแล้ว',
    'status.completed': 'เสร็จสิ้น',
    'status.cancelled': 'ยกเลิก',
    
    // Order Actions
    'action.startPreparing': 'เริ่มเตรียม',
    'action.markReady': 'ทำเครื่องหมายว่าพร้อม',
    'action.completeOrder': 'เสร็จสิ้นคำสั่งซื้อ',
    'action.updating': 'กำลังอัปเดต...',
    
    // Order Details
    'orderDetails.title': 'คำสั่งซื้อ',
    'orderDetails.status': 'สถานะคำสั่งซื้อ',
    'orderDetails.items': 'รายการสินค้า',
    'orderDetails.customer': 'ข้อมูลลูกค้า',
    'orderDetails.details': 'รายละเอียดคำสั่งซื้อ',
    'orderDetails.print': 'พิมพ์',
    'orderDetails.date': 'วันที่สั่งซื้อ',
    'orderDetails.time': 'เวลาสั่งซื้อ',
    'orderDetails.payment': 'การชำระเงิน',
    'orderDetails.paymentMethod': 'เงินสดเมื่อรับสินค้า',
    'orderDetails.specialInstructions': 'คำแนะนำพิเศษ',
    'orderDetails.totalAmount': 'จำนวนเงินรวม',
    'orderDetails.each': 'ต่อชิ้น',
    
    // Sales
    'sales.title': 'แดชบอร์ดยอดขาย',
    'sales.totalOrders': 'คำสั่งซื้อทั้งหมด',
    'sales.totalRevenue': 'รายได้รวม',
    'sales.avgOrderValue': 'มูลค่าเฉลี่ยต่อคำสั่งซื้อ',
    'sales.date': 'วันที่',
    'sales.topItems': 'สินค้าขายดี',
    'sales.export': 'ส่งออก',
    'sales.insights': 'ข้อมูลเชิงลึกการขาย',
    'sales.performance': 'ประสิทธิภาพ',
    'sales.noData': 'ไม่มีข้อมูลยอดขาย',
    
    // Menu
    'menu.title': 'จัดการเมนู',
    'menu.addItem': 'เพิ่มรายการ',
    'menu.search': 'ค้นหารายการเมนู...',
    'menu.allCategories': 'หมวดหมู่ทั้งหมด',
    'menu.allItems': 'รายการทั้งหมด',
    'menu.availableOnly': 'ที่มีอยู่เท่านั้น',
    'menu.unavailableOnly': 'ที่ไม่มีเท่านั้น',
    'menu.available': 'มีอยู่',
    'menu.unavailable': 'ไม่มี',
    'menu.hide': 'ซ่อน',
    'menu.show': 'แสดง',
    'menu.noItems': 'ไม่พบรายการเมนู',
    'menu.unavailableLabel': 'ไม่มีจำหน่าย',
    
    // Menu Form
    'menuForm.addTitle': 'เพิ่มรายการเมนูใหม่',
    'menuForm.editTitle': 'แก้ไขรายการเมนู',
    'menuForm.name': 'ชื่อ',
    'menuForm.nameRequired': 'ชื่อ *',
    'menuForm.nameEn': 'ชื่อ (อังกฤษ) *',
    'menuForm.nameTh': 'ชื่อ (ไทย) *',
    'menuForm.namePlaceholder': 'ชื่อรายการ',
    'menuForm.nameEnPlaceholder': 'ชื่อรายการภาษาอังกฤษ',
    'menuForm.nameThPlaceholder': 'ชื่อรายการภาษาไทย',
    'menuForm.description': 'รายละเอียด',
    'menuForm.descriptionEn': 'รายละเอียด (อังกฤษ)',
    'menuForm.descriptionTh': 'รายละเอียด (ไทย)',
    'menuForm.descriptionPlaceholder': 'รายละเอียดรายการ (ไม่บังคับ)',
    'menuForm.descriptionEnPlaceholder': 'รายละเอียดรายการภาษาอังกฤษ (ไม่บังคับ)',
    'menuForm.descriptionThPlaceholder': 'รายละเอียดรายการภาษาไทย (ไม่บังคับ)',
    'menuForm.basePrice': 'ราคาพื้นฐาน',
    'menuForm.basePriceRequired': 'ราคาพื้นฐาน *',
    'menuForm.basePricePlaceholder': '0.00',
    'menuForm.category': 'หมวดหมู่',
    'menuForm.categoryRequired': 'หมวดหมู่ *',
    'menuForm.categoryEn': 'หมวดหมู่ (อังกฤษ) *',
    'menuForm.categoryTh': 'หมวดหมู่ (ไทย) *',
    'menuForm.categoryPlaceholder': 'เช่น กาแฟ, ชา, ขนมอบ',
    'menuForm.categoryEnPlaceholder': 'e.g., Coffee, Tea, Pastry',
    'menuForm.categoryThPlaceholder': 'เช่น กาแฟ, ชา, ขนมอบ',
    'menuForm.availability': 'สถานะความพร้อม',
    'menuForm.active': 'เปิดใช้งาน',
    'menuForm.inactive': 'ปิดใช้งาน',
    'menuForm.image': 'รูปภาพ',
    'menuForm.imageUrl': 'URL รูปภาพ (ไม่บังคับ)',
    'menuForm.uploadImage': 'อัปโหลดรูปภาพ',
    'menuForm.orEnterUrl': 'หรือใส่ URL ด้านบน',
    'menuForm.customizations': 'ตัวเลือกเพิ่มเติม',
    'menuForm.addCustomization': 'เพิ่ม',
    'menuForm.customizationPlaceholder': 'ชื่อตัวเลือก (เช่น ขนาด, นม, เพิ่มเติม)',
    'menuForm.options': 'ตัวเลือก:',
    'menuForm.addOption': '+ เพิ่มตัวเลือก',
    'menuForm.optionPlaceholder': 'ค่าตัวเลือก',
    'menuForm.remove': 'ลบ',
    'menuForm.saving': 'กำลังบันทึก...',
    'menuForm.uploading': 'กำลังอัปโหลด...',
    'menuForm.update': 'อัปเดต',
    'menuForm.create': 'สร้าง',
    
    // Common
    'common.loading': 'กำลังโหลด...',
    'common.error': 'ข้อผิดพลาด',
    'common.success': 'สำเร็จ',
    'common.cancel': 'ยกเลิก',
    'common.save': 'บันทึก',
    'common.clear': 'ล้าง',
    'common.delete': 'ลบ',
    'common.edit': 'แก้ไข',
    'common.back': 'ย้อนกลับ',
    'common.na': 'ไม่มีข้อมูล',
    'common.phone': 'โทรศัพท์',
    'common.email': 'อีเมล',
    'common.name': 'ชื่อ',
    'common.customer': 'ลูกค้า',
    'common.add': 'เพิ่ม',
    'common.select': 'เลือก',
    'common.unitPrice': 'ราคาต่อหน่วย',
    'common.refresh': 'รีเฟรช',
    'common.view': 'ดู',

    // Create Order
    'createOrder.title': 'สร้างคำสั่งซื้อ',
    'createOrder.menu': 'เมนู',
    'createOrder.searchPlaceholder': 'ค้นหาเมนู...',
    'createOrder.customerInfo': 'ข้อมูลลูกค้า',
    'createOrder.customerNamePlaceholder': 'ชื่อลูกค้า',
    'createOrder.phonePlaceholder': 'เช่น 080-000-0000',
    'createOrder.emailPlaceholder': 'email@example.com',
    'createOrder.notes': 'หมายเหตุ',
    'createOrder.cart': 'ตะกร้า',
    'createOrder.cartEmpty': 'ไม่มีสินค้าในตะกร้า เพิ่มจากเมนู',
    'createOrder.discountCode': 'รหัสส่วนลด',
    'createOrder.items': 'รายการ',
    'createOrder.subtotal': 'ยอดรวมย่อย',
    'createOrder.discount': 'ส่วนลด',
    'createOrder.total': 'รวม',
    'createOrder.placeOrder': 'ยืนยันคำสั่งซื้อ',
    'createOrder.creating': 'กำลังสร้าง...',
    'createOrder.loadingMenu': 'กำลังโหลดเมนู...',
    'createOrder.noMenu': 'ไม่พบรายการเมนู กรุณาเพิ่มในหน้าจัดการเมนูก่อน',
    'createOrder.noDiscount': 'ไม่มีส่วนลด',

    // Settings
    'settings.title': 'ตั้งค่า',
    'settings.appSettings': 'การตั้งค่าแอป',
    'settings.language': 'ภาษา',
    'settings.autoRefreshInterval': 'ช่วงเวลารีเฟรชอัตโนมัติ (วินาที)',
    'settings.currentValue': 'ค่าปัจจุบัน',
    'settings.shop': 'ร้านค้า',
    'settings.clientStatus': 'สถานะของแอปไคลเอนต์คือ',
    'settings.refresh': 'รีเฟรช',
    'settings.refreshing': 'กำลังรีเฟรช...',
    'settings.systemInformation': 'ข้อมูลระบบ',
    'settings.appVersion': 'เวอร์ชันแอป',
    'settings.lastUpdated': 'อัปเดตล่าสุด',
    'settings.browser': 'เบราว์เซอร์',
    'settings.platform': 'แพลตฟอร์ม',
    'settings.saveSettings': 'บันทึกการตั้งค่า',
    'settings.userProfile': 'โปรไฟล์ผู้ใช้',
    'settings.role': 'บทบาท',

    // Dashboard
    'dashboard.todaysRevenue': 'รายได้วันนี้',
    'dashboard.todaysOrders': 'ออเดอร์วันนี้',
    'dashboard.avgOrderValue': 'มูลค่าเฉลี่ยต่อออเดอร์',
    'dashboard.activeOrders': 'ออเดอร์ที่กำลังดำเนินการ',
    'dashboard.completionRate': 'อัตราการเสร็จสิ้น',
    'dashboard.recentOrders': 'ออเดอร์ล่าสุด',
    'dashboard.noOrdersYet': 'ยังไม่มีออเดอร์',
    'dashboard.viewAll': 'ดูทั้งหมด',
    'dashboard.manageOrders': 'จัดการออเดอร์',
    'dashboard.manageOrdersDesc': 'ดูและอัปเดตสถานะออเดอร์',
    'dashboard.menuManagement': 'จัดการเมนู',
    'dashboard.menuManagementDesc': 'อัปเดตรายการและราคาเมนู',
    'dashboard.settings': 'ตั้งค่า',
    'dashboard.settingsDesc': 'ปรับแต่งการตั้งค่าแอป',
    'dashboard.teaCupProgress': 'ความคืบหน้าถ้วยชา',
    'dashboard.record': 'ทำสถิติ!',
    'dashboard.vsYesterday': 'เทียบกับเมื่อวาน',
    'dashboard.toBreak': 'เพื่อทำลายสถิติ',

    // Sales page extra
    // 'sales.title' already defined above
    'sales.hourlyCurve': 'กราฟยอดขายรายชั่วโมง',
    'sales.specificDay': 'วันเฉพาะ',
    'sales.dateRange': 'ช่วงวันที่',
    'sales.allTime': 'ตลอดเวลา',
    'sales.useDateRange': 'ใช้ช่วงวันที่',
    'sales.showAllTime': 'แสดงตลอดเวลา',
    'sales.metric': 'ตัวชี้วัด',
    'sales.revenue': 'รายได้',
    'sales.orders': 'คำสั่งซื้อ',
    'sales.itemsSold': 'จำนวนที่ขาย',
    'sales.noHourlyData': 'ไม่พบข้อมูลรายชั่วโมง',
    'sales.periodAllTime': 'ช่วงการขาย: ตลอดเวลา',
    'sales.periodRange': 'ช่วงการขาย',
    'sales.to': 'ถึง',
    // 'sales.topItems' already defined above
    'sales.rank': 'อันดับ',
    'sales.itemName': 'ชื่อสินค้า',
    'sales.category': 'หมวดหมู่',
    'sales.quantitySold': 'จำนวนที่ขาย',
    'sales.revenueCol': 'รายได้',
    'sales.percentageOfSales': 'เปอร์เซ็นต์ของยอดขาย',
    'sales.revenueInsights': 'ข้อมูลรายได้',
    'sales.completedRevenue': 'รายได้ที่เสร็จสิ้น',
    'sales.bestCategory': 'หมวดหมู่ขายดีที่สุด',
    'sales.highestRevenueItem': 'รายการที่มีรายได้สูงสุด',
    'sales.topItemShare': 'สัดส่วนของสินค้าท็อป',
    'sales.orderPerformance': 'ประสิทธิภาพคำสั่งซื้อ',
    'sales.cancelledRate': 'อัตรายกเลิก',
    'sales.orderCompletionProgress': 'ความคืบหน้าการเสร็จสิ้นคำสั่งซื้อ',
    'sales.ordersCompleted': 'คำสั่งซื้อที่เสร็จสิ้นสำเร็จ',
    'sales.noDataHint': 'ไม่พบข้อมูลการขายสำหรับช่วงที่เลือก โปรดลองปรับช่วงวันที่',
    'sales.retry': 'ลองโหลดข้อมูลอีกครั้ง',
    'sales.startDate': 'วันที่เริ่มต้น',
    'sales.endDate': 'วันที่สิ้นสุด',
    'sales.dailyBreakdown': 'สรุปรายวัน',
    'sales.items': 'รายการ',
    'sales.found': 'ที่พบ',
    'sales.totals': 'รวม',
    'sales.day': 'วัน',
    'sales.rangeLabel': 'ช่วง',
    'sales.noItemsSold': 'ไม่มีสินค้าที่ถูกขาย',
    'sales.totalRevenueLower': 'รายได้รวม',
    'sales.avgPrice': 'ราคาเฉลี่ย',
    
    // Common extra
    'common.status': 'สถานะ',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = safeStorage.getItem('language');
    return (saved as Language) || 'th'; // Default to Thai
  });

  useEffect(() => {
    safeStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
